### ISSUE TITLE
Warning: Header may not contain NUL bytes on php 7.3 (and propably in 7.4)

### ISSUE THREAD

**Issue by bartoszkubicki** [maciejslawik/docker-php-fpm-xdebug#1]
When xdebug on/off function is used there is warning mentioned in title above. It seems it is enough to fix it by upgrading xdebug (`RUN pecl install xdebug-2.9.1`)

**Comment by maciejslawik** [comment]
Both versions (7.3 and 7.4) have been updated to use xdebug 2.9.1
